namespace Game {
    export class ${className} extends cor.BaseScene {
        public readonly skinName = "${className}";

        public ${classIds}
        public ${classProps}

        constructor() {
            super();

            this.init();
            this.initEvent();
        }

        public init() {
            // init
        }

        private initEvent() {
            
        }
    }
}
